/* ===========================================================
   PASO 0 — LIMPIEZA CONTROLADA (DROP TABLE)
   =========================================================== */
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PAGO CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DOSIS CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE RECETA CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE MEDICAMENTO CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TIPO_MEDICAMENTO CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PACIENTE CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE MEDICO CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ESPECIALIDAD CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE COMUNA CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CIUDAD CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE REGION CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE BANCO CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DIAGNOSTICO CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DIGITADOR CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

/* ===========================================================
   CASO 1: MODELO ORIGINAL 
   =========================================================== */

-- 1. TABLA REGION
CREATE TABLE REGION (
    ID_REGION      NUMBER GENERATED ALWAYS AS IDENTITY,
    NOMBRE_REGION  VARCHAR2(100) NOT NULL,
    CONSTRAINT PK_REGION PRIMARY KEY (ID_REGION)
);

-- 2. TABLA ESPECIALIDAD
CREATE TABLE ESPECIALIDAD (
    ID_ESPECIALIDAD     NUMBER GENERATED ALWAYS AS IDENTITY,
    NOMBRE_ESPECIALIDAD VARCHAR2(100) NOT NULL,
    CONSTRAINT PK_ESPECIALIDAD PRIMARY KEY (ID_ESPECIALIDAD)
);

-- 3. TABLA DIAGNOSTICO
CREATE TABLE DIAGNOSTICO (
    ID_DIAGNOSTICO  NUMBER GENERATED ALWAYS AS IDENTITY,
    DESCRIPCION     VARCHAR2(500) NOT NULL,
    CONSTRAINT PK_DIAGNOSTICO PRIMARY KEY (ID_DIAGNOSTICO)
);

-- 4. TABLA TIPO_MEDICAMENTO
CREATE TABLE TIPO_MEDICAMENTO (
    ID_TIPO_MED      NUMBER GENERATED ALWAYS AS IDENTITY,
    NOMBRE_TIPO_MED  VARCHAR2(100) NOT NULL,
    CONSTRAINT PK_TIPO_MEDICAMENTO PRIMARY KEY (ID_TIPO_MED)
);

-- 5. TABLA BANCO
CREATE TABLE BANCO (
    ID_BANCO      NUMBER GENERATED ALWAYS AS IDENTITY,
    NOMBRE_BANCO  VARCHAR2(100) NOT NULL,
    CONSTRAINT PK_BANCO PRIMARY KEY (ID_BANCO)
);

-- 6. TABLA DIGITADOR
CREATE TABLE DIGITADOR (
    RUT_DIGITADOR  VARCHAR2(12) NOT NULL,
    NOMBRE         VARCHAR2(100) NOT NULL,
    CONSTRAINT PK_DIGITADOR PRIMARY KEY (RUT_DIGITADOR)
);

-- 7. TABLA CIUDAD
CREATE TABLE CIUDAD (
    ID_CIUDAD      NUMBER GENERATED ALWAYS AS IDENTITY,
    NOMBRE_CIUDAD  VARCHAR2(100) NOT NULL,
    ID_REGION      NUMBER NOT NULL,
    CONSTRAINT PK_CIUDAD PRIMARY KEY (ID_CIUDAD),
    CONSTRAINT FK_CIUDAD_REGION FOREIGN KEY (ID_REGION) REFERENCES REGION(ID_REGION)
);

-- 8. TABLA COMUNA
CREATE TABLE COMUNA (
    ID_COMUNA      NUMBER GENERATED ALWAYS AS IDENTITY,
    NOMBRE_COMUNA  VARCHAR2(100) NOT NULL,
    ID_CIUDAD      NUMBER NOT NULL,
    CONSTRAINT PK_COMUNA PRIMARY KEY (ID_COMUNA),
    CONSTRAINT FK_COMUNA_CIUDAD FOREIGN KEY (ID_CIUDAD) REFERENCES CIUDAD(ID_CIUDAD)
);

-- 9. TABLA MEDICAMENTO
CREATE TABLE MEDICAMENTO (
    ID_MEDICAMENTO      NUMBER GENERATED ALWAYS AS IDENTITY,
    NOMBRE_MEDICAMENTO  VARCHAR2(100) NOT NULL,
    ID_TIPO_MED         NUMBER NOT NULL,
    CONSTRAINT PK_MEDICAMENTO PRIMARY KEY (ID_MEDICAMENTO),
    CONSTRAINT FK_MED_TIPO FOREIGN KEY (ID_TIPO_MED) REFERENCES TIPO_MEDICAMENTO(ID_TIPO_MED)
);


-- 10. TABLA MEDICO
CREATE TABLE MEDICO (
    RUT_MEDICO      VARCHAR2(12) NOT NULL,
    NOMBRE          VARCHAR2(100) NOT NULL,
    APELLIDO        VARCHAR2(100) NOT NULL,
    ID_ESPECIALIDAD NUMBER NOT NULL,
    CONSTRAINT PK_MEDICO PRIMARY KEY (RUT_MEDICO),
    CONSTRAINT FK_MEDICO_ESPEC FOREIGN KEY (ID_ESPECIALIDAD) REFERENCES ESPECIALIDAD(ID_ESPECIALIDAD)
);

-- 11. TABLA PACIENTE
CREATE TABLE PACIENTE (
    RUT_PACIENTE   VARCHAR2(12) NOT NULL,
    NOMBRE         VARCHAR2(100) NOT NULL,
    APELLIDO       VARCHAR2(100) NOT NULL,
    DIRECCION      VARCHAR2(200) NOT NULL,
    ID_COMUNA      NUMBER NOT NULL,
    CONSTRAINT PK_PACIENTE PRIMARY KEY (RUT_PACIENTE),
    CONSTRAINT FK_PACIENTE_COMUNA FOREIGN KEY (ID_COMUNA) REFERENCES COMUNA(ID_COMUNA)
);



-- 12. TABLA RECETA
CREATE TABLE RECETA (
    ID_RECETA      NUMBER GENERATED ALWAYS AS IDENTITY,
    FECHA_EMISION  DATE NOT NULL,
    RUT_MEDICO     VARCHAR2(12) NOT NULL,
    RUT_PACIENTE   VARCHAR2(12) NOT NULL,
    RUT_DIGITADOR  VARCHAR2(12) NOT NULL,
    ID_DIAGNOSTICO NUMBER NOT NULL,
    CONSTRAINT PK_RECETA PRIMARY KEY (ID_RECETA),
    CONSTRAINT FK_REC_MEDICO FOREIGN KEY (RUT_MEDICO) REFERENCES MEDICO(RUT_MEDICO),
    CONSTRAINT FK_REC_PACIENTE FOREIGN KEY (RUT_PACIENTE) REFERENCES PACIENTE(RUT_PACIENTE),
    CONSTRAINT FK_REC_DIGITADOR FOREIGN KEY (RUT_DIGITADOR) REFERENCES DIGITADOR(RUT_DIGITADOR),
    CONSTRAINT FK_REC_DIAGNOSTICO FOREIGN KEY (ID_DIAGNOSTICO) REFERENCES DIAGNOSTICO(ID_DIAGNOSTICO)
);


-- 13. TABLA DOSIS
CREATE TABLE DOSIS (
    ID_DOSIS        NUMBER GENERATED ALWAYS AS IDENTITY,
    ID_RECETA       NUMBER NOT NULL,
    ID_MEDICAMENTO  NUMBER NOT NULL,
    CANTIDAD        NUMBER NOT NULL,
    INSTRUCCIONES   VARCHAR2(500),
    CONSTRAINT PK_DOSIS PRIMARY KEY (ID_DOSIS),
    CONSTRAINT FK_DOSIS_RECETA FOREIGN KEY (ID_RECETA) REFERENCES RECETA(ID_RECETA),
    CONSTRAINT FK_DOSIS_MEDICAMENTO FOREIGN KEY (ID_MEDICAMENTO) REFERENCES MEDICAMENTO(ID_MEDICAMENTO)
);

-- 14. TABLA PAGO
CREATE TABLE PAGO (
    ID_PAGO    NUMBER GENERATED ALWAYS AS IDENTITY,
    MONTO      NUMBER NOT NULL,
    FECHA_PAGO DATE NOT NULL,
    ID_RECETA  NUMBER NOT NULL,
    ID_BANCO   NUMBER NOT NULL,
    CONSTRAINT PK_PAGO PRIMARY KEY (ID_PAGO),
    CONSTRAINT FK_PAGO_RECETA FOREIGN KEY (ID_RECETA) REFERENCES RECETA(ID_RECETA),
    CONSTRAINT FK_PAGO_BANCO FOREIGN KEY (ID_BANCO) REFERENCES BANCO(ID_BANCO)
);



/* ===========================================================
   CASO 2: MANTENIMIENTO Y MODIFICACIÓN
   =========================================================== */

-- 1. Modificaciones en MEDICAMENTO
ALTER TABLE MEDICAMENTO ADD PRECIO_UNITARIO NUMBER;
ALTER TABLE MEDICAMENTO ADD CONSTRAINT CK_PRECIO_RANGO 
    CHECK (PRECIO_UNITARIO BETWEEN 1000 AND 2000000);

-- 2. Modificaciones en PAGO
ALTER TABLE PAGO ADD METODO_PAGO VARCHAR2(20);
ALTER TABLE PAGO ADD CONSTRAINT CK_METODO_PAGO 
    CHECK (METODO_PAGO IN ('EFECTIVO', 'TARJETA', 'TRANSFERENCIA'));

-- 3. Modificaciones en PACIENTE
ALTER TABLE PACIENTE ADD FECHA_NACIMIENTO DATE;


